version: '3.3'

services:
  wordpress:
    image: wordpress:php7.4-apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql-server
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

volumes:
  db_data: {}
